apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-config
data:
  LOADBALANCEROPERATOR_EVENTS_SUBSCRIBER_PREFIX: "{{ .Values.operator.events.topicPrefix }}"
  LOADBALANCEROPERATOR_EVENTS_SUBSCRIBER_URL: "{{ .Values.operator.events.connectionURL }}"
  LOADBALANCEROPERATOR_EVENTS_QUEUEGROUP: "{{ .Values.operator.events.queueGroup }}"
  LOADBALANCEROPERATOR_API_ENDPOINT: "{{ .Values.operator.api.endpoint }}"
  LOADBALANCEROPERATOR_CHART_PATH: "{{ .Values.operator.chart.chartPath }}"
  LOADBALANCEROPERATOR_CHART_VALUE_PATH: "{{ .Values.operator.chart.valuesPath }}"
  LOADBALANCEROPERATOR_OIDC: "{{ .Values.operator.api.oidc.enabled }}"
  LOADBALANCEROPERATOR_OIDC_AUDIENCE: "{{ .Values.operator.api.oidc.audience }}"
  LOADBALANCEROPERATOR_OIDC_ISSUER: "{{ .Values.operator.api.oidc.issuer }}"
