---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: 
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.operator.extraLabels }}
    {{- toYaml .Values.operator.extraLabels | nindent 4 }}
    {{- end }}
    {{- if .Values.operator.extraAnnotations }}
  annotations:
    {{- toYaml .Values.operator.extraAnnotations | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.operator.replicas | default 1 }}
  revisionHistoryLimit: 3
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: 
      {{- include "common.labels.standard" . | nindent 8 }}
      {{- if .Values.operator.extraLabels }}
      {{- toYaml .Values.operator.extraLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.operator.extraAnnotations }}
      annotations:
        {{- toYaml .Values.operator.extraAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "load-balancer-operator.serviceAccountName" . }}
      {{- if .Values.operator.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.operator.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.operator.extraEnvVars }}
          env:
          {{- range .Values.operator.extraEnvVars }}
            - name: {{ .name }}
              value: {{ .value }}
          {{- end }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "common.names.fullname" . }}-config
          {{- if .Values.operator.securityContext }}
          securityContext:
            {{- toYaml .Values.operator.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - process
          {{- range .Values.operator.events.topics }}
            - --event-topics={{ . }}
          {{- end }}
          {{- range .Values.operator.events.locations }}
            - --event-locations={{ . }}
          {{- end }}
          ports:
            - name: hc
              containerPort: {{ .Values.operator.healthCheckPort | default "8080" }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livez
              port: hc
          volumeMounts:
            - name: chart-config
              mountPath: /chart.tgz
              subPath: chart.tgz
            - name: chart-config
              mountPath: /lb-values.yaml
              subPath: values.yaml
            {{- if .Values.operator.events.auth.secretName  }}
            - name: events-creds
              mountPath: /creds
              subPath: "creds"
            {{- end }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.operator.events.auth.secretName  }}
        - name: events-creds
          secret:
            secretName: "{{ .Values.operator.events.auth.secretName }}"
        {{- end }}
        - name: chart-config
          configMap:
            name: "{{ include "common.names.fullname" . }}-lb-chart"
            

