---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: 
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.operator.extraLabels }}
    {{- toYaml .Values.operator.extraLabels | nindent 4 }}
    {{- end }}
    {{- if .Values.operator.extraAnnotations }}
  annotations:
    {{- toYaml .Values.operator.extraAnnotations | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.operator.replicas | default 1 }}
  revisionHistoryLimit: 3
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: 
      {{- include "common.labels.standard" . | nindent 8 }}
      {{- if .Values.operator.extraLabels }}
      {{- toYaml .Values.operator.extraLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.operator.extraAnnotations }}
      annotations:
        {{- toYaml .Values.operator.extraAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "load-balancer-operator.serviceAccountName" . }}
      {{- if .Values.operator.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.operator.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: LOADBALANCEROPERATOR_CHART_PATH
              value: "/chart.tgz"
            - name: LOADBALANCEROPERATOR_NATS_URL
              value: "{{ .Values.operator.events.connectionURL }}"
            - name: LOADBALANCEROPERATOR_NATS_STREAM_NAME
              value: "{{ .Values.operator.events.queue | default "loadbalanceroperator" }}"
            - name: LOADBALANCEROPERATOR_NATS_SUBJECT_PREFIX
              value: "{{ .Values.operator.events.subjects }}"
          {{- if .Values.operator.events.auth.secretName }}
            - name: LOADBALANCEROPERATOR_NATS_CREDS_FILE
              value: "/creds"
          {{ end }}
          {{ if .Values.operator.chart.valuesPath }}
            - name: LOADBALANCEROPERATOR_CHART_VALUES_PATH
              value: "/lb-values.yaml"
          {{ end }}
          {{- if .Values.operator.securityContext }}
          securityContext:
            {{- toYaml .Values.operator.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - process
          {{- range .Values.operator.chart.valuesCPUFlag }}
            - --helm-cpu-flag={{ . }}
          {{- end }}
          {{- range .Values.operator.chart.valuesMemoryFlag }}
            - --helm-memory-flag={{ . }}
          {{- end }}
          ports:
            - name: hc
              containerPort: {{ .Values.operator.healthCheckPort | default "8080" }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: hc
          readinessProbe:
            httpGet:
              path: /readyz
              port: hc
          volumeMounts:
            - name: chart-config
              mountPath: /chart.tgz
              subPath: chart.tgz
            {{- if ne .Values.operator.chart.valuesPathKey "" }}
            - name: chart-config
              mountPath: /lb-values.yaml
              subPath: values.yaml
#            - name: chart-path
#              mountPath: /chart.tgz
            {{- end }}
            {{- if .Values.operator.events.auth.secretName  }}
            - name: events-creds
              mountPath: /creds
              subPath: "creds"
            {{- end }}
#            {{- if ne .Values.operator.chart.valuesPath "" }}
#            - name: chart-values-path
#              mountPath: {{ .Values.operator.chart.valuesPath }}
#            {{- end }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if ne .Values.operator.chart.valuesPath "" }}
        - name: chart-values-path
          configMap:
            name: "{{ .Values.operator.chart.configMapName }}"
            items:
              - key: values.yaml
                path: values.yaml
      {{- end }}
        - name: chart-path
          configMap:
            name: "{{ .Values.operator.chart.configMapName }}"
            items:
              - key: chart.yaml
                path: chart.yaml
        {{- if .Values.operator.events.auth.secretName  }}
        - name: events-creds
          secret:
            secretName: "{{ .Values.operator.events.auth.secretName }}"
        {{- end }}
        - name: chart-config
          configMap:
            name: "{{ .Values.operator.chart.configMapName }}"
            

