apiVersion: v1
kind: ConfigMap
metadata:
  name: lb-chart
data:
  values.yaml: |
{{ toYaml .Values.operator.chart.chartValues | indent 4}}
binaryData:
  chart.tgz: {{ .Values.operator.chart.chartBinaryData }}
