version: "3.9"

services:
  loadbalanceroperator:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./loadbalanceroperator
    command:
    - process
    depends_on:
      - nats
    environment:
      LOADBALANCEROPERATOR_DEVELOPMENT: true
      LOADBALANCEROPERATOR_NATS_URL: nats
      LOADBALANCEROPERATOR_NATS_STREAM_NAME: "loadbalanceroperator"
      LOADBALANCEROPERATOR_KUBE_CONFIG_PATH: /root/.kube/config
      LOADBALANCEROPERATOR_NATS_SUBJECT_PREFIX: 'events'
      LOADBALANCEROPERATOR_CHART_PATH: /helm/chart.tgz
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: unless-stopped
    volumes:
      - ${LOADBALANCEROPERATOR_CHART_PATH}:/helm/chart.tgz
      - ${LOADBALANCEROPERATOR_KUBE_CONFIG_PATH}:/root/.kube/config
    networks:
      - loadbalanceroperator 

  nats:
    image: nats:latest
    command:
      - --jetstream
    ports:
      - "4222:4222"
    restart: unless-stopped
    networks:
      - loadbalanceroperator 
  nats-init:
    build:
      context: .
      dockerfile: Dockerfile.devel
    depends_on:
      - nats
    restart: on-failure
    command: ["stream", "--server=nats", "add", "loadbalanceroperator", "--subjects=events.>", "--storage=memory", "--replicas=1", "--retention=limits", "--discard=old", "--max-msgs=-1", "--max-msgs-per-subject=-1", "--max-bytes=-1", "--max-age=-1", "--max-msg-size=-1", "--dupe-window='2m0s'", "--no-allow-rollup", "--deny-delete", "--deny-purge"]
    networks:
      - loadbalanceroperator 
  nats-tools:
    build:
      context: .
      dockerfile: Dockerfile.devel
    depends_on:
      - nats
    restart: unless-stopped
    entrypoint: ["/bin/sh"]
    command: ["-c","sleep infinity"]
    networks:
      - loadbalanceroperator  

networks:
  loadbalanceroperator:
