env:
  APP_NAME: ${BUILDKITE_PIPELINE_SLUG}
  GHCR_REPO: ghcr.io/infratographer/${APP_NAME}
  IMAGE_TAG: ${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_COMMIT:0:8}

steps:
  - label: ":golangci-lint: lint :lint-roller:"
    key: "lint"
    plugins:
      - docker#v5.6.0:
          image: "registry.hub.docker.com/golangci/golangci-lint:v1.51"
          command: ["golangci-lint", "run", "-v", "--timeout", "3m0s"]

  - label: ":test_tube: test"
    key: "test"
    env:
      ENVTEST_K8S_VERSION: 1.25.0
    command: |
      echo --- install dependencies
      go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
      echo +++ run tests
      mkdir bin
      KUBEBUILDER_ASSETS="$$(setup-envtest use $${ENVTEST_K8S_VERSION} --bin-dir $(PWD)/bin -p path)" go test -cover -race ./...
    plugins:
      - docker#v5.6.0:
          image: "golang:1.20"
          # command: ["go", "test", "-cover" ,"-race", "./..."]

  - label: ":golang: build"
    key: "gobuild"
    artifact_paths: "bin/${APP_NAME}"
    plugins:
      - docker#v5.6.0:
          image: "golang:1.20"
          environment:
            - CGO_ENABLED=0
            - GOOS=linux
          command: ["go", "build", "-buildvcs=false", "-mod=mod", "-a", "-o", "bin/$APP_NAME"]

  - label: ":docker: docker build and publish"
    key: "build"
    depends_on: ["lint", "test", "gobuild"]
    env:
      BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: "true"
    commands: |
      #!/bin/bash
      echo --- Retrieve Artifacts
      buildkite-agent artifact download "bin/${APP_NAME}" .
      # make sure it is executable
      chmod +x bin/${APP_NAME}
    plugins:
      - docker-login#v2.1.0:
          username: infratographer-releasebot
          password-env: SECRET_GHCR_PUBLISH_TOKEN
          server: ghcr.io
      - equinixmetal-buildkite/docker-metadata#v1.0.0:
          images:
          - "${GHCR_REPO}"
          extra_tags:
          - "${IMAGE_TAG}"
      - equinixmetal-buildkite/docker-build#v1.1.0:
          push: true
          build-args:
            - NAME=${APP_NAME}
      - equinixmetal-buildkite/trivy#v1.16.7:
          severity: CRITICAL
          ignore-unfixed: true
          security-checks: config,secret,vuln
          skip-files: 'cosign.key'
