---
name: Test - Golang

# Run for all pushes to main and pull requests when Go or YAML files change
on:
  push:
  pull_request:

jobs:
  gotest:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s-version: ["1.27", "1.28", "1.29"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - uses: rizzza/envtest-action@patch-1
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s-version }}
        with:
          args: './...'
